spring:
  application:
    name: KeyGenerationService
key:
  generation:
    template: "XXXX-XXXX-XXXX"
cors:
  allowed-origins: "*"
server:
  port: 9002
---
spring:
  config:
    activate:
      on-profile: cloud
  application:
    name: KeyGenerationService
key:
  generation:
    template: "${KEY_CODE_TEMPLATE}" # There are no specified template requirements, the only one is that only 'X'
cors:                                # Character will be replaced with random sign
  allowed-origins: "${ALLOWED_ORIGINS}"
server:
  port: 9002