version: "3.9"

networks:
  kafka_network:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9.0
    container_name: zookeeper
    networks:
      - kafka_network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: docker.io/bitnami/kafka:3.9.0
    container_name: kafka
    networks:
      - kafka_network
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true  
    depends_on:
      zookeeper:
        condition: service_started

  kafka-init:
    image: docker.io/bitnami/kafka:3.9.0
    networks:
      - kafka_network
    command: ["/bin/bash", "-c", "/service_topics_init.sh"]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - type: bind
        source: ./service_topics_init.sh
        target: /service_topics_init.sh
    init: true